namespace _Project.Scripts.Gameplay.Talents
{
    public enum TalentId
    {
        CoreHealthSmall = 0,
        AutoClick = 1,
        CoreClickReduction = 2,
        CoreHealthLarge = 3,
        StingerMoleculeDamageSmall = 4,
        StingerMoleculeAim = 5,
        StingerMoleculePierce = 6,
        LegacyStingerMoleculeAutoLoad = 7,
        StingerMoleculeDamageLarge = 8,
        ExtraBattleMolecule = 9,
        MembraneMolecule = 10,
        MembraneMoleculeChargeReduction = 11,
        MembraneMoleculeDuration = 12,
        LegacyMembraneMoleculeAutoLoad = 13,
        SwarmMolecule = 14,
        SwarmMoleculeDamageSmall = 15,
        LegacySwarmMoleculeAutoLoad = 16,
        SwarmMoleculeDamageLarge = 17,
        CurrencyPickupArea = 18,
        SwarmMoleculeShotCount = 19,
        SwarmMoleculeAttackRange = 20,
        ConnectionAtomSpeed = 21,
        StingerMoleculeCriticalChance = 22,
        StingerMoleculeCriticalReward = 23,
        NucleotideFlatKillReward = 24,
        NucleotideExtraDropChance = 25,
        RadicalDropChance = 26,
        RadicalDropChanceLarge = 27,
        StingerMoleculeChargeReduction = 28,
    }
}
